version: '3.8'
  services:
  init_volumes:
      image: busybox
      volumes:
        - "/mnt:/data"
      command: sh -c 'if [ ! -d "/graylog-datanode" ]; then mkdir -p /graylog-datanode; fi && if [ ! -d "/graylog" ]; then mkdir -p /graylog; fi'
    
    elasticsearch: #is it needed?
      image: docker.elastic.co/elasticsearch/elasticsearch
      enviroment: 
        - discovery.type=single-node
      ports:
        - 9200:9200
      restart: "on-failure"
    
    mongodb:
      image: mongo
      volumes:
        - "mongodb_data:/data/db"
      restart: "on-failure"
    
    graylog:
      image: graylog/graylog
      volumes:
volumes:
  mongodb_data:
  graylog-datanode:
  graylog_data:
  graylog_journal:
